version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/usr/src/app'
    ports:
      - 8000:8000
#    env_file:
#      - env.env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DEBUG: no-debug

    ports:
      - 3000:3000
