version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/usr/src/app"
      - "mediafiles:/usr/src/app/mediafiles"
    ports:
      - "8000:8000"
    env_file:
      - env.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DEBUG: no-debug

    ports:
      - 3000:3000
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - mediafiles:/usr/src/app/mediafiles  # Shared media volume
    ports:
      - "80:80"
    depends_on:
      - backend

  volumes:
    mediafiles: