version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/usr/src/app"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: clinx
      POSTGRES_USER: clinx
      POSTGRES_DB: clinx
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      DEBUG: debug

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DEBUG: debug
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
