# Generated by Django 4.0 on 2022-12-01 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_appointment_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='due_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Due On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start On'),
            preserve_default=False,
        ),
    ]
