# Generated by Django 4.0 on 2022-12-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_appointment_due_time_appointment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.BooleanField(choices=[('Done', 'Done'), ('Pending', 'Pending')]),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], max_length=30),
        ),
    ]
