# Generated by Django 4.0 on 2022-12-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_attachments_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bath',
            name='type_of_bath',
            field=models.CharField(choices=[('full', 'full'), ('half', 'half')], max_length=10, verbose_name='Bath Type'),
        ),
    ]
