# Generated by Django 4.0 on 2022-12-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_bath_type_of_bath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.home'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Resident'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='bath',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bath',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Resident'),
        ),
        migrations.AlterField(
            model_name='bath',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='dailycare',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.home'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='resident_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.attachments'),
        ),
        migrations.AlterField(
            model_name='fluidintake',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fluidintake',
            name='resident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Resident'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fluidintake',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentalstate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mentalstate',
            name='resident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Resident'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentalstate',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mood',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mood',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Resident'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.attachments'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.home'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='resident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Resident'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sleep',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestioncomplains',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.home'),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Resident'),
        ),
        migrations.AlterField(
            model_name='task',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.home'),
        ),
        migrations.AlterField(
            model_name='task',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weight',
            name='resident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Resident'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weight',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff'),
            preserve_default=False,
        ),
    ]
