# Generated by Django 4.0 on 2022-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='height',
            field=models.FloatField(default=1.5, verbose_name='height'),
            preserve_default=False,
        ),
    ]
