# Generated by Django 4.0 on 2022-12-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_resident_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluidintake',
            name='additional_info',
            field=models.TextField(default='', verbose_name='Addational Infomation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluidintake',
            name='amount_offered',
            field=models.FloatField(default=20, verbose_name='Amount Offered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluidintake',
            name='type_of_fluid',
            field=models.CharField(default='', max_length=20, verbose_name='Type Of Fluid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fluidintake',
            name='amount',
            field=models.FloatField(verbose_name='Amount Taken '),
        ),
    ]
