# Generated by Django 4.0 on 2022-12-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_fluidintake_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluidintake',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('womed', 'Womed'), ('annoyed', 'Annoyed')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='fluidintake',
            name='additional_info',
            field=models.TextField(verbose_name='Additional Infomation'),
        ),
    ]
