# Generated by Django 4.0 on 2022-12-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_morningroutine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morningroutine',
            old_name='get_up',
            new_name='getting_up',
        ),
    ]
