# Generated by Django 4.0 on 2022-12-08 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_afternoonroutine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('urinal_incontinence', models.TextField(max_length=20)),
                ('fecal_incontinence', models.TextField(max_length=20)),
                ('catheter', models.TextField(max_length=20)),
                ('stomach_bag', models.TextField(max_length=20)),
                ('fluid_output', models.TextField(max_length=20)),
                ('stool_type', models.CharField(choices=[('1', 'Type 1'), ('2', 'Type 2'), ('3', 'Type 3'), ('4', 'Type 4'), ('5', 'Type 5'), ('6', 'Type 6'), ('7', 'Type 7')], max_length=200)),
                ('emotion', models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('womed', 'Womed'), ('annoyed', 'Annoyed')], default='unknown', max_length=10, verbose_name='Emotion')),
                ('additional_info', models.TextField(verbose_name='Additional Infomation')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Resident')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff')),
            ],
        ),
    ]
