# Generated by Django 4.0 on 2022-12-08 22:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_note_type_of_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestioncomplains',
            old_name='description',
            new_name='action_taken',
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='date_occured',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='family_informed',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='follow_up_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='future_preventative_action',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='inident_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='report_type',
            field=models.CharField(choices=[('accident', 'accident'), ('incident', 'incident'), ('compliment', 'compliment'), ('complaint', 'complaint'), ('suggestion', 'suggestion'), ('near', 'near')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='resident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='status',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='subject',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestioncomplains',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
