# Generated by Django 4.0 on 2022-12-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_userassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.assessment'),
            preserve_default=False,
        ),
    ]
