# Generated by Django 4.0 on 2022-12-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_assignhomeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], max_length=15),
        ),
    ]
