# Generated by Django 4.0 on 2022-12-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_alter_reminder_status'),
        ('management', '0029_food_amount_alter_reminder_status'),
    ]

    operations = [
    ]
