# Generated by Django 4.0 on 2022-12-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_merge_20221221_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'answer', 'evaluation')},
        ),
    ]
