# Generated by Django 4.0 on 2022-12-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_alter_assessment_id_alter_choice_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='score',
        ),
    ]
