# Generated by Django 4.0 on 2022-12-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_alter_evaluation_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'evaluation')},
        ),
    ]
