# Generated by Django 4.0 on 2023-01-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_alter_choice_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='assigned_by',
            new_name='staff',
        ),
    ]
