# Generated by Django 4.0 on 2023-01-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_rename_assigned_by_reminder_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='resident_signature',
            new_name='receipt',
        ),
    ]
