# Generated by Django 4.0 on 2023-01-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_remove_reminder_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='status',
        ),
    ]
