# Generated by Django 4.0 on 2023-01-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_remove_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='management.user', verbose_name='Staff'),
            preserve_default=False,
        ),
    ]
