# Generated by Django 4.0 on 2023-01-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_rename_date_rota_end_date_alter_rota_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminderrota',
            name='rota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Rota'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminderappointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reminderevaluation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reminderrota',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reminderrota',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReminderRota', to='management.user', verbose_name='Reminder'),
        ),
    ]
