# Generated by Django 4.0 on 2023-01-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_appointment_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminderappointment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reminderevaluation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reminderrota',
            name='created_by',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='EvaluationAssessment', to='management.assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminderappointment',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReminderAppointment', to='management.reminder', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='reminderevaluation',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReminderEvaluation', to='management.reminder', verbose_name='Reminder'),
        ),
        migrations.AlterField(
            model_name='reminderrota',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReminderRota', to='management.reminder', verbose_name='Reminder'),
        ),
        migrations.CreateModel(
            name='EvaluationScheduler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluation', models.CharField(max_length=20, verbose_name='Evaluation')),
                ('evalution_date', models.DateTimeField()),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReminderEvaluationScheduler', to='management.user', verbose_name='Reminder')),
            ],
        ),
    ]
