# Generated by Django 4.0 on 2023-01-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_remove_reminderappointment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationscheduler',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReminderEvaluationScheduler', to='management.reminder', verbose_name='Reminder'),
        ),
        migrations.AlterField(
            model_name='reminderappointment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.appointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='reminderevaluation',
            name='valuation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.evaluation', verbose_name='Evaluation'),
        ),
        migrations.AlterField(
            model_name='reminderrota',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.rota', verbose_name='Rota'),
        ),
    ]
