# Generated by Django 4.0 on 2023-01-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_alter_evaluationscheduler_reminder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='assigned_residents',
        ),
    ]
