# Generated by Django 4.0 on 2023-01-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_remove_rota_assigned_residents'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rota',
            unique_together=set(),
        ),
    ]
