# Generated by Django 4.0 on 2023-01-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_alter_rota_end_date_alter_rota_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='assigned_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RotaHome', to='management.home', verbose_name='Home'),
        ),
    ]
