# Generated by Django 4.0 on 2023-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_alter_reminderevaluationscheduler_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
