# Generated by Django 4.0 on 2023-02-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_alter_user_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_on']},
        ),
    ]
