# Generated by Django 4.0 on 2023-02-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0057_alter_posibleanswear_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supportplan',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='supportplan',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='supportplan',
            name='status',
        ),
        migrations.AddField(
            model_name='supportplan',
            name='achievements',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='action_plan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='by_when',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='by_who',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='by_whom',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportplan',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='goal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='issue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='RiskActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('identified_risk', models.CharField(blank=True, max_length=30, null=True)),
                ('details', models.TextField(null=True)),
                ('triggers', models.TextField(null=True)),
                ('support_needs', models.CharField(blank=True, max_length=30, null=True)),
                ('information_sources_used', models.CharField(choices=[('APPLICANT', 'APPLICANT'), ('CARERS/FRIENDS', 'CARERS/FRIENDS'), ('REFERRER', 'REFERRER'), ('OTHER AGENCIES', 'OTHER AGENCIES')], default='REFERRER', max_length=50)),
                ('is_further_information_needed', models.BooleanField(default=False)),
                ('yes_no', models.BooleanField(default=False)),
                ('assesment_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='')),
            ],
        ),
    ]
