# Generated by Django 4.0 on 2023-02-11 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_riskactionplan_created_on_supportplan_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskactionplan',
            name='category',
            field=models.CharField(choices=[('Care Plan', 'Care Plan'), ('Risk Assessment', 'Risk Assesssment'), ('General Assessment', 'Medical'), ('Support Plan', 'Suppot Plan')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportplan',
            name='category',
            field=models.CharField(choices=[('Care Plan', 'Care Plan'), ('Risk Assessment', 'Risk Assesssment'), ('General Assessment', 'Medical'), ('Support Plan', 'Suppot Plan')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportplan',
            name='resident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name=''),
            preserve_default=False,
        ),
    ]
