# Generated by Django 4.0 on 2023-02-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0060_riskactionplan_category_supportplan_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskactionplan',
            name='yes_no',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Yes', 'Yes'), ('No', 'No')], default='Unknown', max_length=40),
        ),
    ]
