# Generated by Django 4.0 on 2023-02-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0062_alter_riskactionplan_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='comment',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
