# Generated by Django 4.0 on 2023-02-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0064_alter_reminderevaluationscheduler_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderrota',
            name='reminder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ReminderRota', to='management.reminder', verbose_name='Reminder'),
        ),
    ]
