# Generated by Django 4.0 on 2023-02-25 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_family_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestioncomplains',
            name='family_informed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.family'),
        ),
        migrations.AlterField(
            model_name='suggestioncomplains',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.resident', verbose_name='Family'),
        ),
    ]
