# Generated by Django 4.0 on 2023-02-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_alter_suggestioncomplains_family_informed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextofKeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.family')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.resident')),
            ],
            options={
                'unique_together': {('resident', 'family')},
            },
        ),
    ]
