# Generated by Django 4.0 on 2023-02-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0069_nextofkeen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkeen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
