# Generated by Django 4.0 on 2023-02-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0070_alter_nextofkeen_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='management.user')),
                ('outgoing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='management.user')),
            ],
        ),
    ]
