# Generated by Django 4.0 on 2023-02-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0071_handoverpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestioncomplains',
            name='subject',
            field=models.CharField(max_length=60),
        ),
    ]
