# Generated by Django 4.0 on 2023-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_sleep_additional_info_sleep_emotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
