# Generated by Django 4.0 on 2023-03-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0074_alter_family_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
