# Generated by Django 4.0 on 2023-03-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0076_note_emotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_on']},
        ),
    ]
