# Generated by Django 4.0 on 2023-03-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='resident',
            field=models.ForeignKey(default='PE098781B', on_delete=django.db.models.deletion.CASCADE, to='management.resident'),
        ),
    ]
