# Generated by Django 4.0 on 2023-03-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_note_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='resident',
            field=models.ForeignKey(default='7573475286', on_delete=django.db.models.deletion.CASCADE, to='management.resident'),
        ),
    ]
