# Generated by Django 4.0 on 2023-03-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0079_alter_note_resident'),
        ('management', '0079_resident_nhs_number_alter_note_resident'),
    ]

    operations = [
    ]
