# Generated by Django 4.0 on 2023-03-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0079_resident_nhs_number_alter_note_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='afternoonroutine',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='continence',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='fluidintake',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='food',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='morningroutine',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='note',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='pressureareacare',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('tearful', 'Tearful'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
    ]
