# Generated by Django 4.0 on 2023-03-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0080_alter_activity_emotion_and_more'),
        ('management', '0080_merge_20230310_1735'),
    ]

    operations = [
    ]
