# Generated by Django 4.0 on 2023-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0082_alter_note_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='training',
            field=models.TextField(blank=True, null=True),
        ),
    ]
