# Generated by Django 4.0 on 2023-03-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0087_alter_finance_tag_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='type',
            field=models.CharField(choices=[('GeneralInfo', 'GeneralInfo'), ('Psychiatrist', 'Psychiatrist'), ('Optician', 'Optician'), ('SocialWorker', 'SocialWorker'), ('Family', 'Family')], default='Family', max_length=30),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='category',
            field=models.CharField(choices=[('GP', 'GP'), ('Resident', 'Resident'), ('Finance', 'Finance'), ('Home', 'Home')], max_length=60),
        ),
    ]
