# Generated by Django 4.0 on 2023-03-25 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0089_remove_handoverpayment_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportScheduler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evalution_date', models.DateTimeField()),
                ('support_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SupportScheduler', to='management.supportplan', verbose_name='SupportPlan')),
            ],
        ),
        migrations.CreateModel(
            name='RiskScheduler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evalution_date', models.DateTimeField()),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RiskScheduler', to='management.riskactionplan', verbose_name='RiskActionPlan')),
            ],
        ),
    ]
