# Generated by Django 4.0 on 2023-03-25 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0091_riskscheduler_reminder_alter_riskactionplan_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskactionplan',
            name='assesment_date',
        ),
        migrations.AddField(
            model_name='riskactionplan',
            name='next_assement_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On'),
            preserve_default=False,
        ),
    ]
