# Generated by Django 4.0 on 2023-03-25 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0092_remove_riskactionplan_assesment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportplan',
            name='date',
        ),
        migrations.AddField(
            model_name='supportplan',
            name='next_assement_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Asssment date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='next_assement_date',
            field=models.DateTimeField(verbose_name='Asssment date'),
        ),
    ]
