# Generated by Django 4.0 on 2023-03-25 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0097_remove_reminderevaluationscheduler_evaluation_scheduler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestioncomplains',
            name='discontinue',
            field=models.BooleanField(default=False, verbose_name='Discontibnue'),
        ),
        migrations.AddField(
            model_name='suggestioncomplains',
            name='next_assement_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Asssment date'),
        ),
    ]
