# Generated by Django 4.0 on 2023-03-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0099_evaluation_discontinue_riskactionplan_discontinue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestioncomplains',
            name='review_date',
        ),
        migrations.CreateModel(
            name='SuggestionComplainsScheduler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('evalution_date', models.DateTimeField()),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.suggestioncomplains', verbose_name='SuggestionComplains')),
                ('reminder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SuggestionComplainsReminder', to='management.reminder', verbose_name='Reminder')),
            ],
        ),
    ]
