# Generated by Django 4.0 on 2023-03-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0100_remove_suggestioncomplains_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestioncomplains',
            name='family_informed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.family'),
        ),
    ]
