# Generated by Django 4.0 on 2023-03-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0101_alter_suggestioncomplains_family_informed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RotaCreated', to='management.user', verbose_name='Created BY'),
        ),
    ]
