# Generated by Django 4.0 on 2023-03-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0102_rota_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='recur',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='no', max_length=50),
        ),
    ]
