# Generated by Django 4.0 on 2023-03-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0104_alter_rota_end_date_alter_rota_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='recur',
        ),
    ]
