# Generated by Django 4.0 on 2023-03-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0105_remove_rota_recur'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='finance',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Receipt Number'),
        ),
    ]
