# Generated by Django 4.0 on 2023-03-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0106_finance_attachment_finance_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportscheduler',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SupportPlanScheduler', to='management.reminder', verbose_name='Reminder'),
        ),
    ]
