# Generated by Django 4.0 on 2023-04-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0107_supportscheduler_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
