# Generated by Django 4.0 on 2023-04-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0108_alter_finance_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='type',
            field=models.CharField(choices=[('GeneralInfo', 'GeneralInfo'), ('Psychiatrist', 'Psychiatrist'), ('Optician', 'Optician'), ('SocialWorker', 'SocialWorker'), ('Family', 'Family'), ('CareCoordinator', 'Care Coordinator')], default='Family', max_length=30),
        ),
    ]
