# Generated by Django 4.0 on 2023-04-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0109_alter_family_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='gender',
        ),
        migrations.AddField(
            model_name='family',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
