# Generated by Django 4.0 on 2023-04-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0110_remove_family_gender_family_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='handoverpayment',
            options={'ordering': ['-created_on']},
        ),
    ]
