# Generated by Django 4.0 on 2023-04-10 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0111_alter_finance_options_alter_handoverpayment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMaps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_plan', models.CharField(blank=True, max_length=30, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('comment', models.TextField(blank=True, null=True)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('pain', models.IntegerField()),
                ('condition', models.CharField(blank=True, max_length=30, null=True)),
                ('attachment', models.FileField(upload_to='attachments')),
                ('next_assement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Asssment date')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.resident')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff')),
            ],
        ),
    ]
