# Generated by Django 4.0 on 2023-04-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0112_bodymaps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BodyMaps',
            new_name='BodyMap',
        ),
    ]
