# Generated by Django 4.0 on 2023-04-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0116_residentdischarge_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentdischarge',
            name='type',
            field=models.CharField(choices=[('checkin', 'checkin'), ('checkout', 'checkout')], default='checkin', max_length=50),
        ),
    ]
