# Generated by Django 4.0 on 2023-04-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0117_residentdischarge_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignHomeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_name', to='management.user', verbose_name='assignedBy')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.home')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Stafdf')),
            ],
        ),
    ]
