# Generated by Django 4.0 on 2023-04-24 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0118_assignhomestaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignhomestaff',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='management.user', verbose_name='assigned_by'),
        ),
    ]
