# Generated by Django 4.0 on 2023-04-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0119_alter_assignhomestaff_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymap',
            name='accident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.suggestioncomplains'),
        ),
    ]
