# Generated by Django 4.0 on 2023-06-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0120_bodymap_accident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continence',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='continence',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='family',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='food',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='food',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='staff',
        ),
        migrations.AlterUniqueTogether(
            name='nextofkeen',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nextofkeen',
            name='family',
        ),
        migrations.RemoveField(
            model_name='nextofkeen',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='pressureareacare',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='pressureareacare',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='suggestioncomplains',
            name='family_informed',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Continence',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='NextofKeen',
        ),
        migrations.DeleteModel(
            name='PressureAreaCare',
        ),
    ]
