# Generated by Django 4.0 on 2023-07-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0121_remove_continence_resident_remove_continence_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='next_of_kin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='assignhomestaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='discontinue',
            field=models.BooleanField(default=False, verbose_name='Discontinue'),
        ),
    ]
