# Generated by Django 4.0 on 2023-07-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0122_resident_next_of_kin_alter_assignhomestaff_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='relative',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
