# Generated by Django 4.0 on 2023-07-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0126_rename_posibleanswear_posibleanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
