# Generated by Django 4.0 on 2023-08-15 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0128_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
