# Generated by Django 4.0 on 2023-08-15 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0130_alter_inventoryitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='management.user'),
        ),
    ]
