# Generated by Django 4.0 on 2023-08-16 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0132_alter_inventoryitem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='management.user', to_field='email'),
        ),
    ]
