# Generated by Django 4.0 on 2023-08-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0133_alter_inventoryitem_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='created_by',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
