# Generated by Django 4.0 on 2023-08-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0135_remove_inventoryitem_created_by_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestioncomplains',
            old_name='inident_details',
            new_name='incident_details',
        ),
    ]
