# Generated by Django 4.0 on 2023-08-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0136_rename_inident_details_suggestioncomplains_incident_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='Created by'),
        ),
    ]
