# Generated by Django 4.0 on 2023-08-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0137_alter_inventoryitem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.user'),
        ),
    ]
