# Generated by Django 4.0 on 2023-08-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0139_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
