# Generated by Django 4.0 on 2023-09-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0142_inventoryitem_deleted_alter_resident_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
