# Generated by Django 4.0 on 2023-09-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0145_user_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('date_of_acquisition', models.DateField()),
                ('condition', models.CharField(max_length=100)),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.home')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.user')),
            ],
            options={
                'ordering': ['-recorded_on'],
            },
        ),
    ]
