# Generated by Django 4.0 on 2023-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0146_houseassets'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseassets',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
