# Generated by Django 4.0 on 2023-09-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0147_houseassets_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseassets',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.home'),
        ),
    ]
