# Generated by Django 4.0 on 2023-09-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0149_housestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='housestock',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='housestock',
            name='date_of_acquisition',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='housestock',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='housestock',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.user'),
        ),
    ]
