# Generated by Django 4.0 on 2023-09-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0150_housestock_created_on_housestock_date_of_acquisition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housestock',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.home'),
        ),
        migrations.AddField(
            model_name='housestock',
            name='if_perishable',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
