# Generated by Django 4.0 on 2023-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0151_housestock_house_housestock_if_perishable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housestock',
            name='quantity',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
