# Generated by Django 4.0 on 2023-09-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0152_alter_housestock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housestock',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
