# Generated by Django 4.0 on 2023-09-21 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0156_repairrecord_recorded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseassets',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.home'),
        ),
    ]
