# Generated by Django 4.0 on 2023-09-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0157_alter_houseassets_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='housestock',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
