# Generated by Django 4.0 on 2023-09-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0158_housestock_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseassets',
            name='value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
