# Generated by Django 4.0 on 2023-10-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0162_deletionrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionrecords',
            name='stock_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.housestock'),
        ),
        migrations.AlterField(
            model_name='deletionrecords',
            name='date_deleted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
