# Generated by Django 4.0 on 2023-10-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0163_deletionrecords_stock_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionrecords',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='housestock',
            name='deletion_reason',
            field=models.TextField(blank=True, default='Not deleted', null=True),
        ),
    ]
