# Generated by Django 4.0 on 2023-10-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0164_deletionrecords_reason_housestock_deletion_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseassets',
            name='deletion_reason',
            field=models.TextField(blank=True, default='Not deleted', null=True),
        ),
        migrations.AddField(
            model_name='repairrecord',
            name='deletion_reason',
            field=models.TextField(blank=True, default='Not deleted', null=True),
        ),
    ]
