# Generated by Django 4.0 on 2023-10-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0165_houseassets_deletion_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_reason',
            field=models.TextField(blank=True, default='Not deleted', null=True),
        ),
    ]
