# Generated by Django 4.0 on 2023-10-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0166_user_deletion_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_reason',
            field=models.TextField(blank=True, default='Enabled', null=True),
        ),
    ]
