# Generated by Django 4.0 on 2023-10-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0168_repairrecord_priority_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentdischarge',
            name='is_discharged_status',
            field=models.BooleanField(default=False),
        ),
    ]
