# Generated by Django 4.0 on 2023-10-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0169_residentdischarge_is_discharged_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='NHS_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Trur',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pova_checked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='smoker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekly_contracted_hour',
        ),
    ]
