# Generated by Django 4.0 on 2023-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0171_alter_appointment_recur'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deletion_reason',
            field=models.TextField(blank=True, default='Not deleted', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
