# Generated by Django 4.0 on 2023-10-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0172_appointment_deletion_reason_appointment_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='entry',
        ),
    ]
