# Generated by Django 4.0 on 2023-10-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0174_confidentialrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confidentialrecord',
            name='attachment',
        ),
    ]
