# Generated by Django 4.0 on 2023-10-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0175_remove_confidentialrecord_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidentialrecord',
            name='deletion_reason',
            field=models.TextField(default='Not deleted'),
        ),
        migrations.AddField(
            model_name='confidentialrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
