# Generated by Django 4.0 on 2023-10-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0176_confidentialrecord_deletion_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deletion_reason',
            field=models.TextField(blank=True, default='Not deleted', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
