# Generated by Django 4.0 on 2023-11-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0178_allowedlocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(blank=True, to='management.AllowedLocations'),
        ),
    ]
