# Generated by Django 4.0 on 2023-11-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0180_allowedusergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedlocations',
            name='allowed_groups',
            field=models.ManyToManyField(to='management.AllowedUserGroup'),
        ),
    ]
