# Generated by Django 5.0.4 on 2024-07-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0187_remove_user_location_remove_user_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportplan',
            name='approved_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='care_rating',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=40, null=True, verbose_name='Care Rating'),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='cp_duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='afternoonroutine',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='fluidintake',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='morningroutine',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='note',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
    ]
