# Generated by Django 5.0.4 on 2024-07-11 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0189_remove_supportplan_by_whom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportplan',
            name='last_evaluated_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
