# Generated by Django 5.0.4 on 2024-07-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0190_supportplan_last_evaluated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportplan',
            name='achievements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='action_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
