# Generated by Django 5.0.4 on 2024-07-11 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0191_alter_supportplan_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportplan',
            name='last_evaluated_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
