# Generated by Django 5.0.4 on 2024-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0192_alter_supportplan_last_evaluated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportplan',
            name='last_evaluated_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
