# Generated by Django 5.0.4 on 2024-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0193_alter_supportplan_last_evaluated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportplan',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='last_evaluated_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
