# Generated by Django 5.0.4 on 2024-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0194_alter_supportplan_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportplan',
            name='last_evaluated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
