# Generated by Django 5.0.4 on 2024-07-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0196_alter_riskactionplan_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskactionplan',
            name='category',
            field=models.CharField(choices=[('HousingTenancy', 'Housing/Tenancy'), ('FinanceMoneyBenefitManagement', 'Finance/Money/Benefit Management'), ('RentArrearsServiceUsers', 'Rent Arrears - Service Users'), ('Education', 'Education'), ('Training', 'Training'), ('Employment', 'Employment'), ('MentalHealthSubstanceUse', 'Mental Health/Substance Use'), ('EthnicCulturalReligiousNeeds', 'Ethnic/Cultural/Religious Needs -'), ('LeisureSocialNetwork', 'LeisureSocialNetwork'), ('MovingOn', 'Moving On'), ('FurtherConcernsNeeds', 'Further Concerns/Needs -'), ('ServicesProvidedByHousingOrEstateManagementService', 'Services provided by Housing or Estate Management Service'), ('ServicesProvidedBySupportWorker', 'Services provided by Support Worker'), ('SupportWorkersViewsofIssuesNeedsorActions', "Support Worker's Views of Issues, Needs or Actions")], default='Risk', max_length=100),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='category',
            field=models.CharField(choices=[('HousingTenancy', 'Housing/Tenancy'), ('FinanceMoneyBenefitManagement', 'Finance/Money/Benefit Management'), ('RentArrearsServiceUsers', 'Rent Arrears - Service Users'), ('Education', 'Education'), ('Training', 'Training'), ('Employment', 'Employment'), ('MentalHealthSubstanceUse', 'Mental Health/Substance Use'), ('EthnicCulturalReligiousNeeds', 'Ethnic/Cultural/Religious Needs -'), ('LeisureSocialNetwork', 'LeisureSocialNetwork'), ('MovingOn', 'Moving On'), ('FurtherConcernsNeeds', 'Further Concerns/Needs -'), ('ServicesProvidedByHousingOrEstateManagementService', 'Services provided by Housing or Estate Management Service'), ('ServicesProvidedBySupportWorker', 'Services provided by Support Worker'), ('SupportWorkersViewsofIssuesNeedsorActions', "Support Worker's Views of Issues, Needs or Actions")], max_length=100),
        ),
    ]
