# Generated by Django 5.0.4 on 2024-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0197_alter_riskactionplan_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportplan',
            name='staff',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='discontinue',
            field=models.BooleanField(default=False, verbose_name='Discontinue'),
        ),
    ]
