# Generated by Django 5.0.4 on 2024-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0207_alter_supportplan_cp_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportplan',
            name='deletion_reason',
            field=models.TextField(blank=True, default='Not deleted', null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
