# Generated by Django 5.0.4 on 2024-07-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0210_supportplan_next_eval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportplan',
            name='evaluations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
