# Generated by Django 5.0.4 on 2024-07-31 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0211_supportplan_evaluations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('support_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.supportplan')),
            ],
        ),
    ]
