# Generated by Django 5.0.4 on 2024-07-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0212_planevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planevaluation',
            name='created_by',
        ),
    ]
