# Generated by Django 5.0.4 on 2024-07-31 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0213_remove_planevaluation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='planevaluation',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.resident'),
        ),
        migrations.AddField(
            model_name='planevaluation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
