# Generated by Django 5.0.4 on 2024-08-06 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0214_planevaluation_resident_planevaluation_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='planevaluation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
