# Generated by Django 5.0.4 on 2024-09-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0215_planevaluation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskactionplan',
            name='at_risk',
            field=models.CharField(blank=True, choices=[('Service User', 'Service User'), ('Staff', 'Staff'), ('Family Member', 'Family Member'), ('Other', 'Other')], max_length=40, null=True, verbose_name='Who is at risk?'),
        ),
        migrations.AddField(
            model_name='riskactionplan',
            name='likelihood',
            field=models.CharField(blank=True, choices=[('Unlikely', 'Unlikely'), ('May Happen', 'May Happen'), ('Likely', 'Likely')], max_length=40, null=True, verbose_name='Likelihood'),
        ),
        migrations.AddField(
            model_name='riskactionplan',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=40, null=True, verbose_name='Risk Levels'),
        ),
        migrations.AddField(
            model_name='riskactionplan',
            name='severity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=40, null=True, verbose_name='Severity'),
        ),
    ]
