# Generated by Django 5.0.4 on 2024-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0216_riskactionplan_at_risk_riskactionplan_likelihood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtRiskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='riskactionplan',
            name='at_risk',
        ),
        migrations.AddField(
            model_name='riskactionplan',
            name='at_risk',
            field=models.ManyToManyField(to='management.atriskoption'),
        ),
    ]
