# Generated by Django 5.0.4 on 2024-09-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0218_alter_atriskoption_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afternoonroutine',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=30, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='afternoonroutine',
            name='getting_dressed',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='afternoonroutine',
            name='getting_up',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='afternoonroutine',
            name='oral_care',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='afternoonroutine',
            name='prompting',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='afternoonroutine',
            name='shaving',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='afternoonroutine',
            name='toilet_use',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='afternoonroutine',
            name='washing',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bath',
            name='type_of_bath',
            field=models.CharField(choices=[('full', 'full'), ('half', 'half')], max_length=20, verbose_name='Bath Type'),
        ),
        migrations.AlterField(
            model_name='bodymap',
            name='condition',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bodymap',
            name='treatment_plan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fluidintake',
            name='type_of_fluid',
            field=models.CharField(max_length=100, verbose_name='Type Of Fluid'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping')], default='unknown', max_length=20, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='morningroutine',
            name='getting_dressed',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='morningroutine',
            name='getting_up',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='morningroutine',
            name='oral_care',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='morningroutine',
            name='prompting',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='morningroutine',
            name='shaving',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='morningroutine',
            name='toilet_use',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='morningroutine',
            name='washing',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='national_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='next_of_kin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='at_risk',
            field=models.ManyToManyField(choices=[('Service User', 'Service User'), ('Staff', 'Staff'), ('Family Member', 'Family Member'), ('Other', 'Other')], to='management.atriskoption'),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='identified_risk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='shift',
            field=models.CharField(choices=[('Night', 'Night'), ('Day', 'Day'), ('Off', 'Off')], max_length=40),
        ),
        migrations.AlterField(
            model_name='suggestioncomplains',
            name='status',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=40),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='action_plan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='by_when',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='by_who',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='goal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='issue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ethnic_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50),
        ),
    ]
