# Generated by Django 5.0.4 on 2024-09-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0219_alter_afternoonroutine_emotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskactionplan',
            name='approved_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
