# Generated by Django 5.0.4 on 2024-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0220_riskactionplan_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='recur',
            field=models.CharField(choices=[('no', 'No'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('norecur', 'NoRecur')], default='norecur', max_length=50),
        ),
    ]
