# Generated by Django 4.0 on 2024-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0221_alter_appointment_recur'),
    ]

    operations = [
        #migrations.AddField(
         #   model_name='user',
         #   name='location',
         #   field=models.CharField(blank=True, max_length=255, null=True),
       # ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='at_risk',
            field=models.ManyToManyField(choices=[('Service User', 'Service User'), ('Staff', 'Staff'), ('Family Member', 'Family Member'), ('Other', 'Other')], to='management.AtRiskOption'),
        ),
    ]
