# Generated by Django 5.0.4 on 2025-01-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0222_alter_supportplan_issue_alter_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='allergies',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='clinical_diagnosis',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='risk',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='achievements',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='action_plan',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='evaluations',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='goal',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='issue',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist_name', models.CharField(max_length=100)),
                ('dentist_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dentist_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentist', to='management.resident')),
            ],
        ),
        migrations.CreateModel(
            name='GP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_name', models.CharField(max_length=100)),
                ('gp_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gp', to='management.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharma_name', models.CharField(max_length=100)),
                ('pharma_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('pharma_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist', to='management.resident')),
            ],
        ),
        migrations.CreateModel(
            name='SocialWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_name', models.CharField(max_length=100)),
                ('sw_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('sw_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_worker', to='management.resident')),
            ],
        ),
    ]
