# Generated by Django 5.0.4 on 2025-02-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0223_resident_allergies_resident_clinical_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportplan',
            name='achievements',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='action_plan',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='by_who',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='goal',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
