# Generated by Django 4.0 on 2025-06-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0225_alter_supportplan_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskactionplan',
            name='category',
        ),
        migrations.AddField(
            model_name='resident',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='ethnic_origin',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='resident',
            name='marital_status',
            field=models.CharField(default='NonApplicable', max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='medical_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='support_plans'),
        ),
        migrations.AlterField(
            model_name='afternoonroutine',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping'), ('tearful', 'Tearful')], default='unknown', max_length=30, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='fluidintake',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping'), ('tearful', 'Tearful')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping'), ('tearful', 'Tearful')], default='unknown', max_length=20, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='morningroutine',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping'), ('tearful', 'Tearful')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='note',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping'), ('tearful', 'Tearful')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='planevaluation',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='clinical_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='risk',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='room',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='approved_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='at_risk',
            field=models.ManyToManyField(choices=[('Service User', 'Service User'), ('Staff', 'Staff'), ('Family Member', 'Family Member'), ('Other', 'Other')], to='management.AtRiskOption'),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='identified_risk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='likelihood',
            field=models.CharField(blank=True, choices=[('Unlikely', 'Unlikely'), ('May Happen', 'May Happen'), ('Likely', 'Likely')], max_length=100, null=True, verbose_name='Likelihood'),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='support_needs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping'), ('tearful', 'Tearful')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='approved_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='by_when',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='by_who',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='care_rating',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Care Rating'),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='category',
            field=models.CharField(choices=[('HousingTenancy', 'Housing/Tenancy'), ('FinanceMoneyBenefitManagement', 'Finance/Money/Benefit Management'), ('RentArrearsServiceUsers', 'Rent Arrears - Service Users'), ('Education', 'Education'), ('Training', 'Training'), ('Employment', 'Employment'), ('MentalHealthSubstanceUse', 'Mental Health/Substance Use'), ('EthnicCulturalReligiousNeeds', 'Ethnic/Cultural/Religious Needs -'), ('LeisureSocialNetwork', 'LeisureSocialNetwork'), ('MovingOn', 'Moving On'), ('FurtherConcernsNeeds', 'Further Concerns/Needs -'), ('ServicesProvidedByHousingOrEstateManagementService', 'Services provided by Housing or Estate Management Service'), ('ServicesProvidedBySupportWorker', 'Services provided by Support Worker'), ('SupportWorkersViewsofIssuesNeedsorActions', "Support Worker's Views of Issues, Needs or Actions"), ('PhysicalHealth', 'Physical Health ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='evaluations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='emotion',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('happy', 'Happy'), ('joyful', 'Joyful'), ('sad', 'Sad'), ('content', 'Content'), ('worried', 'Worried'), ('fearful', 'Fearful'), ('sleepy', 'Sleepy'), ('confused', 'Confused'), ('angry', 'Angry'), ('annoyed', 'Annoyed'), ('sleeping', 'Sleeping'), ('tearful', 'Tearful')], default='unknown', max_length=10, verbose_name='Emotion'),
        ),
        migrations.CreateModel(
            name='SupportPlanFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_plans/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='management.supportplan')),
            ],
        ),
    ]
