# Generated by Django 5.2 on 2025-05-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0226_resident_ethnic_origin_resident_marital_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="allergies",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resident",
            name="clinical_diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resident",
            name="risk",
            field=models.CharField(blank=True, null=True),
        ),
    ]
