# Generated by Django 5.2 on 2025-05-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0227_alter_resident_allergies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resident",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="resident",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="height"),
        ),
        migrations.AlterField(
            model_name="resident",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Contact"
            ),
        ),
    ]
