# Generated by Django 5.2 on 2025-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0228_alter_resident_address_alter_resident_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="room",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
