# Generated by Django 5.2 on 2025-05-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0229_alter_resident_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="ethnic_origin",
            field=models.CharField(default="Unknown", max_length=30),
        ),
        migrations.AlterField(
            model_name="resident",
            name="marital_status",
            field=models.CharField(default="NonApplicable"),
        ),
    ]
