# Generated by Django 5.2 on 2025-05-19 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0230_alter_resident_ethnic_origin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportPlanFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="support_plans/")),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="management.supportplan",
                    ),
                ),
            ],
        ),
    ]
