# Generated by Django 5.2 on 2025-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0231_supportplanfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportplan",
            name="attachment",
            field=models.FileField(
                blank=True, default=False, null=True, upload_to="support_plans"
            ),
        ),
    ]
