# Generated by Django 5.2 on 2025-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0232_supportplan_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportplan",
            name="attachment",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="support_plans"
            ),
        ),
    ]
