# Generated by Django 5.2 on 2025-05-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0233_alter_supportplan_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="date_of_admission",
            field=models.DateField(blank=True, null=True),
        ),
    ]
