# Generated by Django 5.2 on 2025-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0234_resident_date_of_admission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskactionplan",
            name="category",
        ),
        migrations.AlterField(
            model_name="supportplan",
            name="care_rating",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Care Rating"
            ),
        ),
    ]
