# Generated by Django 5.2 on 2025-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0235_remove_riskactionplan_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planevaluation",
            name="text",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="supportplan",
            name="achievements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supportplan",
            name="action_plan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supportplan",
            name="approved_by",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supportplan",
            name="by_when",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supportplan",
            name="by_who",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supportplan",
            name="evaluations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supportplan",
            name="goal",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supportplan",
            name="issue",
            field=models.TextField(blank=True, null=True),
        ),
    ]
