# Generated by Django 5.2 on 2025-05-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0236_alter_planevaluation_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskactionplan",
            name="approved_by",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="riskactionplan",
            name="identified_risk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="riskactionplan",
            name="likelihood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Unlikely", "Unlikely"),
                    ("May Happen", "May Happen"),
                    ("Likely", "Likely"),
                ],
                null=True,
                verbose_name="Likelihood",
            ),
        ),
        migrations.AlterField(
            model_name="riskactionplan",
            name="support_needs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="riskactionplan",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
