# Generated by Django 5.2 on 2025-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0237_alter_riskactionplan_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestioncomplains",
            name="discontinue",
            field=models.BooleanField(default=False, verbose_name="Discontinue"),
        ),
        migrations.AlterField(
            model_name="suggestioncomplains",
            name="next_assement_date",
            field=models.DateTimeField(),
        ),
    ]
