# Generated by Django 4.0 on 2025-06-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0238_alter_suggestioncomplains_discontinue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='allergies',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='marital_status',
            field=models.CharField(default='NonApplicable', max_length=9999),
        ),
        migrations.AlterField(
            model_name='resident',
            name='risk',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='at_risk',
            field=models.ManyToManyField(choices=[('Service User', 'Service User'), ('Staff', 'Staff'), ('Family Member', 'Family Member'), ('Other', 'Other')], to='management.AtRiskOption'),
        ),
        migrations.AlterField(
            model_name='riskactionplan',
            name='likelihood',
            field=models.CharField(blank=True, choices=[('Unlikely', 'Unlikely'), ('May Happen', 'May Happen'), ('Likely', 'Likely')], max_length=9999, null=True, verbose_name='Likelihood'),
        ),
    ]
