# Generated by Django 4.0 on 2025-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0239_alter_resident_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notify_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
