# Generated by Django 4.0 on 2025-07-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0240_appointment_notify_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='ethnic_origin',
        ),
    ]
