# Generated by Django 4.0 on 2025-09-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0241_remove_resident_ethnic_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestioncomplains',
            name='next_assement_date',
        ),
    ]
