# Generated by Django 4.0 on 2025-09-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0242_remove_suggestioncomplains_next_assement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestioncomplains',
            name='next_assement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
