# Generated by Django 4.0 on 2025-10-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0226_remove_riskactionplan_category_and_more'),
        ('management', '0243_suggestioncomplains_next_assement_date'),
    ]

    operations = [
    ]
