# Generated by Django 4.0 on 2025-10-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0244_merge_20251002_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskactionplan',
            name='likelihood',
            field=models.CharField(blank=True, choices=[('Unlikely', 'Unlikely'), ('May Happen', 'May Happen'), ('Likely', 'Likely')], max_length=1000, null=True, verbose_name='Likelihood'),
        ),
    ]
